return {
    "mason-org/mason.nvim",
    opts = {
        ensure_installed = {
            "stylua",
            "shellcheck",
            "shfmt",
            "bash-language-server",
            "checkmake",
            "css-lsp",
            "docker-compose-language-service",
            "dockerfile-language-server",
            "eslint-lsp",
            "go-debug-adapter",
            "goimports",
            "golangci-lint",
            "golangci-lint-langserver",
            "gopls",
            "gotests",
            "html-lsp",
            "htmlhint",
            "iferr",
            "impl",
            "intelephense",
            "json-lsp",
            "lua-language-server",
            "marksman",
            "misspell",
            "php-cs-fixer",
            "prettier",
            "pyright",
            "typescript-language-server",
            "vetur-vls",
            "yaml-language-server",
            "yamlfmt",
        },
    },
}
